apiVersion: v1
kind: ConfigMap
metadata:
  name: insurance-app-config
  namespace: insurance-application
data:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  NEXTAUTH_URL: "http://your-domain.com"  # Update this with your actual domain
  DATABASE_URL: "postgresql://postgres:your-db-password@postgres-service:5432/insurance_db"
